before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq tmux zsh git
language: go
go:
  - 1.2
install:
  - script/bootstrap
  - export PATH="$HOME/gopath/bin:$PATH"
  - rvm use 2.1.0 --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - ruby --version
  - rvm --version
  - gem --version
  - script/cached-bundle install --deployment --without development
script:
  - script/build
  - script/test
  - bundle exec rake features PROFILE=all
env:
  global:
    - AMAZON_S3_BUCKET=gh-bundler-cache
    - AMAZON_ACCESS_KEY_ID=AKIAIJR3XZXZC6W44DWA
    - secure: Erd5l/uRvYlim+EW45Edz22lB2SNEPBCA3utk0wv6ZVgz/Ybs6p68dzpEqFFwxhHz8vaYT+lYXonZvV6fXk3sd826cl69mzSQJl/b/AJdCM5ubX9pYenghrA0xQ83J81mTBYxh4ghMH7TBNv0eHuow2RFuNhWlPsS1ziBTZzmP0=
